export const availableOptions: string[] = [
  'GPS',
  'Aer Conditionat',
  'Scaune Încălzite',
  'Cameră 360°',
  'Bluetooth',
  'Pilot Automat',
  'Senzori Parcare',
  'Cameră Marsarier',
  'Lumini LED',
  'Interior Piele',
  'Keyless Entry',
  'Cruise Control',
];

export const brandOptions = [
  { value: 'BMW', label: 'BMW' },
  { value: 'Audi', label: 'Audi' },
  { value: 'Mercedes', label: 'Mercedes' },
  { value: 'Volkswagen', label: 'Volkswagen' },
  { value: 'Toyota', label: 'Toyota' },
  { value: 'Honda', label: 'Honda' },
  { value: 'Ford', label: 'Ford' },
  { value: 'Chevrolet', label: 'Chevrolet' },
  { value: 'Nissan', label: 'Nissan' },
  { value: 'Hyundai', label: 'Hyundai' },
  { value: 'Kia', label: 'Kia' },
  { value: 'Renault', label: 'Renault' },
  { value: 'Peugeot', label: 'Peugeot' },
  { value: 'Citroen', label: 'Citroen' },
  { value: 'Fiat', label: 'Fiat' },
  { value: 'Opel', label: 'Opel' },
  { value: 'Skoda', label: 'Skoda' },
  { value: 'Seat', label: 'Seat' },
  { value: 'Volvo', label: 'Volvo' },
  { value: 'Mazda', label: 'Mazda' },
  { value: 'Mitsubishi', label: 'Mitsubishi' },
  { value: 'Suzuki', label: 'Suzuki' },
  { value: 'Lexus', label: 'Lexus' },
  { value: 'Infiniti', label: 'Infiniti' },
  { value: 'Jaguar', label: 'Jaguar' },
  { value: 'Land Rover', label: 'Land Rover' },
  { value: 'Porsche', label: 'Porsche' },
  { value: 'Ferrari', label: 'Ferrari' },
  { value: 'Lamborghini', label: 'Lamborghini' },
  { value: 'Bentley', label: 'Bentley' },
  { value: 'Rolls-Royce', label: 'Rolls-Royce' },
  { value: 'Aston Martin', label: 'Aston Martin' },
  { value: 'McLaren', label: 'McLaren' },
  { value: 'Bugatti', label: 'Bugatti' },
  { value: 'Alfa Romeo', label: 'Alfa Romeo' },
  { value: 'Maserati', label: 'Maserati' },
  { value: 'Lancia', label: 'Lancia' },
  { value: 'Saab', label: 'Saab' },
  { value: 'Smart', label: 'Smart' },
  { value: 'Mini', label: 'Mini' },
  { value: 'Dacia', label: 'Dacia' },
  { value: 'Lada', label: 'Lada' },
  { value: 'Trabant', label: 'Trabant' },
  { value: 'Moskvich', label: 'Moskvich' },
  { value: 'ZAZ', label: 'ZAZ' },
  { value: 'UAZ', label: 'UAZ' },
  { value: 'GAZ', label: 'GAZ' },
  { value: 'ZIL', label: 'ZIL' },
  { value: 'Volga', label: 'Volga' },
  { value: 'Zhiguli', label: 'Zhiguli' },
  { value: 'Alta', label: 'Alta' },
];

export const colorOptions = [
  { value: 'Alb', label: 'Alb' },
  { value: 'Negru', label: 'Negru' },
  { value: 'Gri', label: 'Gri' },
  { value: 'Albastru', label: 'Albastru' },
  { value: 'Rosu', label: 'Rosu' },
  { value: 'Verde', label: 'Verde' },
  { value: 'Galben', label: 'Galben' },
  { value: 'Portocaliu', label: 'Portocaliu' },
  { value: 'Violet', label: 'Violet' },
  { value: 'Maro', label: 'Maro' },
  { value: 'Argintiu', label: 'Argintiu' },
  { value: 'Auriu', label: 'Auriu' },
  { value: 'Alta', label: 'Alta' },
];

export const carTypeOptions = [
  { value: 'SUV', label: 'SUV' },
  { value: 'Coupe', label: 'Coupe' },
  { value: 'Sedan', label: 'Sedan' },
  { value: 'Hatchback', label: 'Hatchback' },
  { value: 'Convertible', label: 'Convertible' },
  { value: 'Wagon', label: 'Wagon' },
  { value: 'Pickup', label: 'Pickup' },
  { value: 'Van', label: 'Van' },
  { value: 'Other', label: 'Altul' },
];

export const transmissionOptions = [
  { value: 'Manual', label: 'Manuală' },
  { value: 'Automatic', label: 'Automată' },
  { value: 'Semi-Automatic', label: 'Semi-automată' },
];

export const iconOptions = [
  { value: 'Wrench', label: 'Revizie' },
  { value: 'FileText', label: 'RAR' },
  { value: 'Droplet', label: 'Schimb Ulei' },
  { value: 'Calendar', label: 'Eveniment' },
  { value: 'Other', label: 'Altul' },
];

export const tractionOptions = [
  { value: 'integrala', label: 'Integrala (4x4)' },
  { value: 'fata', label: 'Față' },
  { value: 'spate', label: 'Spate' },
];

export const quests = [
  {
    id: 'post-quest',
    title: 'Postează 5 articole',
    description: 'Creează și postează 5 articole pentru a câștiga recompense.',
    progress: 15,
    total: 20,
    reward: '5 Postări Gratuite',
    type: 'posts',
  },
  {
    id: 'friends-quest',
    title: 'Adaugă 10 prieteni',
    description: 'Conectează-te cu 10 prieteni pentru a crește rețeaua socială.',
    progress: 8,
    total: 10,
    reward: 'Insignă "Social"',
    type: 'friends',
  },
  {
    id: 'points-quest',
    title: 'Acumulează 200 puncte',
    description: 'Cumpără sau vinde articole pentru a acumula 200 puncte.',
    progress: 120,
    total: 200,
    reward: 'Acces Premium',
    type: 'points',
  },
  {
    id: 'verify-email',
    title: 'Verifică email-ul',
    description: 'Verifică adresa de email pentru securitate crescută.',
    progress: 0,
    total: 1,
    reward: 'Insignă "Verificat"',
    type: 'verification',
  },
];

export const rewards = [
  {
    id: 'free-posts',
    title: 'Postări Gratuite',
    description: 'Primești 5 postări gratuite pentru vânzări.',
    claimed: false,
    available: true,
  },
  {
    id: 'premium-access',
    title: 'Acces Premium',
    description: 'Acces nelimitat la vânzări și funcții premium.',
    claimed: false,
    available: false,
  },
  {
    id: 'badge-social',
    title: 'Insignă Social',
    description: 'Insignă specială pentru conexiuni sociale.',
    claimed: false,
    available: true,
  },
  {
    id: 'verify-email',
    title: 'Insignă Verificat',
    description: 'Insignă pentru cont verificat.',
    claimed: false,
    available: false,
  },
];

export const proTips = [
  'Postează anunțuri gratuite pentru vânzarea mașinilor tale!',
  'Conectează-te cu alți pasionați de auto pe platformă!',
  'Folosește filtrele pentru a găsi mașina perfectă!',
  'Participă la evenimente și târguri auto!',
  'Verifică-ți email-ul pentru securitate maximă!',
  'Adaugă fotografii de înaltă calitate pentru anunțurile tale!',
  'Comentează și interacționează cu alți utilizatori!',
  'Creează povești pentru a împărtăși experiențele tale!',
  'Folosește funcția de favorite pentru a salva anunțuri interesante!',
  'Actualizează-ți profilul pentru a atrage mai mulți cumpărători!',
  'Explorează categoriile pentru a descoperi oferte speciale!',
  'Împărtășește profilul tău pentru a crește vizibilitatea!',
  'Folosește chat-ul pentru a negocia direct cu vânzătorii!',
  'Creează liste de dorințe pentru viitorul tău vehicul!',
  'Participă la sondaje pentru a câștiga recompense!',
];
