export interface Car {
  id: number;
  title: string;
  price: number;
  year: number;
  brand: string;
  category: 'sell' | 'buy' | 'rent' | 'auction';
  mileage: number;
  fuel: string;
  transmission: string;
  location: string;
  images: string[]; // Changed to array
  dateAdded: string;
  sellerType: 'private' | 'firm';
  contactPhone: string;
  contactEmail: string;
  bodyType: string;
  color: string;
}

export const mockCars: Car[] = [
  {
    id: 1,
    title: 'BMW X3',
    price: 25000,
    year: 2020,
    brand: 'BMW',
    category: 'sell',
    mileage: 50000,
    fuel: 'Diesel',
    transmission: 'Automatic',
    location: 'Bucharest',
    images: ['/placeholder-car.jpg', '/placeholder-car2.jpg', '/placeholder-car3.jpg'], // Array of images
    dateAdded: '2023-10-01',
    sellerType: 'private',
    contactPhone: '+40 123 456 789',
    contactEmail: 'seller1@example.com',
    bodyType: 'SUV',
    color: 'Black',
  },
  {
    id: 2,
    title: 'Audi A4',
    price: 30000,
    year: 2019,
    brand: 'Audi',
    category: 'buy',
    mileage: 40000,
    fuel: 'Petrol',
    transmission: 'Manual',
    location: 'Cluj',
    images: ['/placeholder-car.jpg', '/placeholder-car2.jpg'],
    dateAdded: '2023-09-15',
    sellerType: 'firm',
    contactPhone: '+40 987 654 321',
    contactEmail: 'seller2@example.com',
    bodyType: 'Sedan',
    color: 'White',
  },
  {
    id: 3,
    title: 'Mercedes C-Class',
    price: 35000,
    year: 2021,
    brand: 'Mercedes',
    category: 'rent',
    mileage: 30000,
    fuel: 'Hybrid',
    transmission: 'Automatic',
    location: 'Timisoara',
    images: ['/placeholder-car.jpg'],
    dateAdded: '2023-11-01',
    sellerType: 'private',
    contactPhone: '+40 456 789 123',
    contactEmail: 'seller3@example.com',
    bodyType: 'Coupe',
    color: 'Silver',
  },
  {
    id: 4,
    title: 'VW Golf',
    price: 20000,
    year: 2018,
    brand: 'VW',
    category: 'auction',
    mileage: 60000,
    fuel: 'Petrol',
    transmission: 'Manual',
    location: 'Iasi',
    images: ['/placeholder-car.jpg', '/placeholder-car2.jpg', '/placeholder-car3.jpg'],
    dateAdded: '2023-08-20',
    sellerType: 'firm',
    contactPhone: '+40 321 654 987',
    contactEmail: 'seller4@example.com',
    bodyType: 'Hatchback',
    color: 'Blue',
  },
  {
    id: 5,
    title: 'Toyota Corolla',
    price: 18000,
    year: 2017,
    brand: 'Toyota',
    category: 'sell',
    mileage: 70000,
    fuel: 'Petrol',
    transmission: 'Manual',
    location: 'Constanta',
    images: ['/placeholder-car.jpg'],
    dateAdded: '2023-07-10',
    sellerType: 'private',
    contactPhone: '+40 654 321 098',
    contactEmail: 'seller5@example.com',
    bodyType: 'Sedan',
    color: 'Red',
  },
  {
    id: 6,
    title: 'Honda Civic',
    price: 22000,
    year: 2019,
    brand: 'Honda',
    category: 'buy',
    mileage: 45000,
    fuel: 'Petrol',
    transmission: 'Automatic',
    location: 'Brasov',
    images: ['/placeholder-car.jpg', '/placeholder-car2.jpg'],
    dateAdded: '2023-06-05',
    sellerType: 'firm',
    contactPhone: '+40 789 012 345',
    contactEmail: 'seller6@example.com',
    bodyType: 'Coupe',
    color: 'Gray',
  },
  {
    id: 7,
    title: 'Ford Focus',
    price: 16000,
    year: 2016,
    brand: 'Ford',
    category: 'rent',
    mileage: 80000,
    fuel: 'Diesel',
    transmission: 'Manual',
    location: 'Sibiu',
    images: ['/placeholder-car.jpg', '/placeholder-car2.jpg', '/placeholder-car3.jpg'],
    dateAdded: '2023-05-20',
    sellerType: 'private',
    contactPhone: '+40 123 789 456',
    contactEmail: 'seller7@example.com',
    bodyType: 'Hatchback',
    color: 'Green',
  },
  {
    id: 8,
    title: 'Nissan Qashqai',
    price: 28000,
    year: 2020,
    brand: 'Nissan',
    category: 'auction',
    mileage: 35000,
    fuel: 'Hybrid',
    transmission: 'Automatic',
    location: 'Oradea',
    images: ['/placeholder-car.jpg'],
    dateAdded: '2023-04-15',
    sellerType: 'firm',
    contactPhone: '+40 456 123 789',
    contactEmail: 'seller8@example.com',
    bodyType: 'SUV',
    color: 'White',
  },
  {
    id: 9,
    title: 'Hyundai Tucson',
    price: 24000,
    year: 2019,
    brand: 'Hyundai',
    category: 'sell',
    mileage: 55000,
    fuel: 'Petrol',
    transmission: 'Automatic',
    location: 'Ploiesti',
    images: ['/placeholder-car.jpg', '/placeholder-car2.jpg'],
    dateAdded: '2023-03-10',
    sellerType: 'private',
    contactPhone: '+40 789 456 123',
    contactEmail: 'seller9@example.com',
    bodyType: 'SUV',
    color: 'Black',
  },
  {
    id: 10,
    title: 'Kia Sportage',
    price: 26000,
    year: 2021,
    brand: 'Kia',
    category: 'buy',
    mileage: 25000,
    fuel: 'Diesel',
    transmission: 'Manual',
    location: 'Galati',
    images: ['/placeholder-car.jpg', '/placeholder-car2.jpg', '/placeholder-car3.jpg'],
    dateAdded: '2023-02-05',
    sellerType: 'firm',
    contactPhone: '+40 321 987 654',
    contactEmail: 'seller10@example.com',
    bodyType: 'SUV',
    color: 'Blue',
  },
  // Add more as needed
];
